name: Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build source
      shell: cmd
      run: |
        cd build/android/
        build.bat

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pkcs11-mock-android
        path: build/android/libs/
