name: iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Build source
      run: |
        cd build/ios/
        sh build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pkcs11-mock-ios
        path: build/ios/libpkcs11-mock-*.a
